# -*- coding: utf-8 -*-
"""gyobobookcrawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHsY3OjpuWfPMv1j29qR6jpRwlKDuAV1
"""

from urllib import request, parse
from bs4 import BeautifulSoup as bs

txt_f = open("./bookchart.txt","w")

data = parse.urlencode({'perPage':'50'}).encode()
req = request.Request('http://www.kyobobook.co.kr/bestSellerNew/bestseller.laf', data=data)
html = request.urlopen(req)

bsObject = bs(html, "html.parser")
week_standard = bsObject.find('h4', {'class':'title_best_basic'}).find('small').text
bestseller_contents = bsObject.find('ul', {'class':'list_type01'})
bestseller_list = bestseller_contents.findAll('div', {'class':'detail'})
title_list = [b.find('div', {'class': 'title'}).find('strong').text for b in bestseller_list]

print(week_standard)
for i in range(len(title_list)):
    print("제목: "+title_list[i])
    txt_f.write(f'제목: {title_list[i]} \n')

txt_f.close()